import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ClientProviders from "@/components/ClientProviders";

import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";
import { createServerSupabaseClient } from "@/supabase/server";

import { shadcn } from "@clerk/themes";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const supabase = await createServerSupabaseClient();

    return (
        <ClerkProvider
            appearance={{
                baseTheme: shadcn,
            }}
        >
            <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    <ClientProviders>{children}</ClientProviders>
                </body>
            </html>
        </ClerkProvider>
    );
}
